### ISSUE TITLE
could authentication memberof ldap group login？

### ISSUE THREAD

**Issue by Zhengyueewee2e** [BookStackApp/website#126]
BookStack Version: v22.07

my .env profille
![image](https://user-images.githubusercontent.com/40627010/186375880-bfe0d966-bf80-4e17-b9d7-41afef6ae734.png)
I have created role
![image](https://user-images.githubusercontent.com/40627010/186378022-c608e73d-d9a1-4f2d-9dd9-4844d77af72e.png)

my user：
CN=azheng，OU=test,DC=test,DC=com
CN=azheng3，OU=test2,DC=test,DC=com
my group
CN=test,OU=test,DC=test,DC=com
azheng and azheng3 are in the group
when LDAP_BASE_DN="ou=test,dc=test,dc=com"
azheng can login
azheng3 can't login error messages:user or password wrong

when LDAP_BASE_DN="dc=test,dc=com"
azheng and azheng3 can login both,and  two user are in this test role
![image](https://user-images.githubusercontent.com/40627010/186378440-f3721e16-bd26-4973-8b17-db15c7d212bc.png)

the ldap group sync can't let user log through users are not in the LDAP_BASE_DN?

**Comment by ssddanbrown** [comment]
Hi @Zhengyueewee2e,
This repo is for website/documentation related issues only, so I'll be closing this off.

> the ldap group sync can't let user log through users are not in the LDAP_BASE_DN?

The group sync does not control user access to login, it's somewhat unrelated although group discovery may be affected by `LDAP_BASE_DN`. 

`LDAP_BASE_DN` will affect the discovery of users and groups since searchers will be performed using this DN as the base.

Group sync is performed on returned `memberOf` style returned properties only. Groups within the `LDAP_BASE_DN` setting are not used directly as part of group sync.
