### ISSUE TITLE
Missing 'HttpOnly' Cookie Attribute (HTTP)

### ISSUE THREAD

**Issue by ducarrozb** [BookStackApp/website#184]
Installation: Ubuntu 22.04 LTS

**Security Issue:**

> The remote HTTP web server / application is missing to set the 'HttpOnly' cookie attribute for one or more sent HTTP cookie.
> The flaw exists if a session cookie is not using the 'HttpOnly' cookie attribute.
> This allows a cookie to be accessed by JavaScript which could lead to session hijacking attacks.

- https://medium.com/@yadav-ajay/using-httponly-and-secure-cookies-on-web-servers-how-to-do-it-52ccf0eabfb4
- https://owasp.org/www-community/HttpOnly

` a2enmod headers`

adding ...
```
<IfModule mod_headers.c>
    Header always edit Set-Cookie (.*) "$1; HttpOnly."
</IfModule>
```
...to apache2.conf or to bookstack.conf does not solve the problem.

Any ideas?
Would be nice to add/correct the problem in the default installation.

**Comment by ssddanbrown** [comment]
@ducarrozb Please confirm exactly what cookie you're referring to that you'd consider a security issue in this context.

**Comment by ducarrozb** [comment]
@ssddanbrown 

![Screenshot 2024-04-09 at 14 12 53](https://github.com/BookStackApp/website/assets/83638420/2bda10e2-b383-4dd7-a5ee-c5e7305e378d)

**Comment by ssddanbrown** [comment]
@ducarrozb thanks for providing the detail.

I don't really see making the XSRF token HttpOnly adding any reasonable security benefit here since, following the scenario in the "Vulnerability Insight" section, the XSRF token could just be read from the DOM anyway.
While the XSRF token is session based, it is not the user session itself.

If you do forsee some security risk here feel free to explain it within the context of this application and specific use of cookie to help me understand any actual risk/concerns.

**Comment by ducarrozb** [comment]
Hmm, not sure if hackers see that the same way than you:

- https://www.perplexity.ai/search/Apache-fix-Missing-7eI5FlMzT1m14oaeI30Iqg#0
- https://www.rfc-editor.org/rfc/rfc6265#section-5.2.6
- https://owasp.org/www-community/HttpOnly
- https://wiki.owasp.org/index.php/Testing_for_Session_Management_Schema_(OTG-SESS-001)

As you can see in the report the cookie could lead to session hijacking attacks.
As told above, I tried to insert 

```
<IfModule mod_headers.c>
    Header always edit Set-Cookie (.*) "$1; HttpOnly."
</IfModule>
```

in different files, but the problem persists. I wonder just in which file I have to add these lines, since this would be the solution of the problem

**Comment by ssddanbrown** [comment]
@ducarrozb None of those links indicate why the lack of HttpOnly for a XSRF token (which is already in the HTML) cookie would be an issue.  I understand how HttpOnly can help security and where it's useful (like for sessions where it's already used) but otherwise I'm not sure why we need to make this change for the XSRF token outside of not throwing an alter in the specific automated scanner you use.

**Comment by D4thToMS** [comment]
Hi,

I have the same problem here. When scaning for vulnerabilities the bookstack website comes up with "Set the 'HttpOnly' cookie attribute for any session cookie". 
In the Apache config we set the VIrtualHost to force these secure cookies:
```
<VirtualHost bookstack.mydomain.tld:443>
    Header always edit Set-Cookie ^(.*)$ "$1;HttpOnly;Secure"
    ...
</VirtualHost>
```
Apache us up to date, the module mod_headers.so is loaded.

What can we do ?

Many thanks

**Comment by D4thToMS** [comment]
Perfect ! That's easier I'll ask all vulnerability scanner to make an exception 🥇
