### ISSUE TITLE
Azure AD Authentication issue

### ISSUE THREAD

**Issue by onlinejul** [BookStackApp/website#53]
Hi everyone,

sorry to bother but I tried to configure Azure AD authentication to Bookstack following the doc here : https://www.bookstackapp.com/docs/admin/third-party-auth/#azuread-microsoft.

Unfortunately, I get the following error after clicking on the button "Login with Microsoft Azure" in debug mode : 

Client error: `POST https://login.microsoftonline.com/common/oauth2/token` resulted in a `401 Unauthorized` response:\n
{"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: b4b25216-9 (truncated...)\n

From what I have read, it seems that the secret configured in Azure should be urlEncoded but I have tried various settings int .env file none of which seem to work : 

example 1 : AZURE_APP_SECRET={xxxxx%3xxxxxx%5bxxxxxxxx}
example 2: AZURE_APP_SECRET='{xxxxx%3xxxxxx%5bxxxxxxxx}'
example 3: AZURE_APP_SECRET={'xxxxx%3xxxxxx%5bxxxxxxxx'}
example 4 (not urlEncoded) : AZURE_APP_SECRET={xxxxxxxxxxxxxxxxxxx}

Is there anything I am missing ?

Thank you for your help, good day to the whole team.

Julien

**Comment by ssddanbrown** [comment]
Hi @onlinejul,

Just had a play with this, Seems things in Azure AD have changed a little since I originally wrote the docs. 

Anyway, Here are some things to check:

* Remove any `{` or `}` from the value, unless Azure AD is provided them.
* You should not need to URL encode the value, System should do that automatically.
* You could try wrapping the value in double quotes (`AZURE_APP_SECRET="abc123"`)
* You could try re-generating a secret on Azure, may just be giving you some particularly tricky characters. 

As an example, I just generated a new key and using the below in my `.env` file worked okay:

```bash
AZURE_APP_SECRET=v48jwSTqTki0c=-L8bjpihSWvm=HbEd=
```

Azure provided me `v48jwSTqTki0c=-L8bjpihSWvm=HbEd=` as the key.

Also, Just to confirm, are you using the following area to get your key:?

![image](https://user-images.githubusercontent.com/8343178/73617673-20677800-4619-11ea-8d7a-546fdf8530be.png)

**Comment by onlinejul** [comment]
Hi Dan,

it worked without putting the brackets around the APP_SECRET. 

However, in order for the login to work, I had to go to profile et and click on "Connect Account" under "Social Account" but I guess that this is the expected behaviour ?

Thank you for your help anyway.

Regards,

Julien

**Comment by ssddanbrown** [comment]
Hi @onlinejul,

BookStack airs on the side of safety where possible when it comes to user-matching logic. Upon login BookStack will try to match the azure user to an existing user based on a stored azure id. If not found, BookStack will reject the login or , if `AZURE_AUTO_REGISTER` is enabled, register them as a new user.

If `AZURE_AUTO_REGISTER` is disabled, the instance would need to have the `Registration Enabled` option active and the user would need to visit the register page to gain access, without being invited.

On either registration options, I think BookStack will throw an error if an existing user exists with the given email.

I think this only works for you when manually connecting the account since you already have a BookStack user using the same email address. It may work as expected for a completely fresh user. 

> Then, I deleted the user in Bookstack and logged on directly with the button "Connect with Microsoft Azure". It works but the user is not mapped to its LDAP groups and therefore, does not have the proper permissions to the shelves.

The `AZURE_*` options are for OAuth-based auth systems and we don't support group sync for these. Group sync only exists for LDAP and SAML2 (coming in next release) auth options. I'm not overly familiar with Azure AD but you might be able to configure AzureAD for LDAP or SAML2.

**Comment by onlinejul** [comment]
Dan,

the original question was answered and I believe what I asked if more of general considerations about the architecture of it so let's close the ticket but I'll look into your recommendations about AzureAD for LDAP or SAML2.

So thank you for your help.

Julien
