### ISSUE TITLE
Add documentation for installing to Alpine Linux (and using LXC)

### ISSUE THREAD

**Issue by Doom4535** [BookStackApp/website#57]
I'm not sure what the best way to add this is, so I've attached a markdown file (as .txt) for how I've walked through and setup a LXC container using Alpine for BookStack.
[BookStackLXC_Install_Alpine.txt](https://github.com/BookStackApp/website/files/4242894/BookStackLXC_Install_Alpine.txt)

**Comment by ssddanbrown** [comment]
Thanks a lot for offering this but I'd only really want to support highly-popular LTS systems (Ubuntu LTS or CentOS) in the official docs since we need to ensure we can support people if they are following our official docs. 

Hopefully others searching the web may find this issue or, if you have these details on a page or blog, i'd be happy to link out from the BookStack docs.
